import {
  calendar,
  calendarOutline,
  musicalNotes,
  musicalNotesOutline,
  micOutline,
  pinOutline,
  personOutline,
  timeOutline,
  flagOutline,
  createOutline,
  logInOutline,
  addOutline,
  trashOutline,
  close,
  mapOutline,
  listOutline,
  mapSharp,
} from 'ionicons/icons';

export const icons = {
  calendar,
  calendarOutline,
  musicalNotes,
  musicalNotesOutline,
  micOutline,
  pinOutline,
  personOutline,
  timeOutline,
  flagOutline,
  createOutline,
  logInOutline,
  addOutline,
  trashOutline,
  close,
  mapOutline,
  listOutline,
  mapSharp,
};
