export enum RouteName {
  Tabs = 'tabs',
  Map = 'map',
  Artist = 'artist',
  Timetable = 'timetable',
  Search = 'search',
  Login = 'login',
  Partners = 'partners',
  Profile = 'profile',
  About = 'about',
  Event = 'event',
  Settings = 'settings',
  Tickets = 'tickets',
  Favorite = 'favorite',
  Transport = 'transport',
  Gadearmbaand = 'gadearmbaand',
}
